# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jonathan Rogers - Student Portfolio
email: jrogers4895@cabarrus.k12.nc.us
description: >- # this means to ignore newlines until "baseurl:"
  High School Portfolio of Jonathan Rogers, a student at Northwest Cabarrus High School.
# twitter_username: username
github_username: jonathan-rogers-dev
minimal_mistakes_skin: dirt
search: true

# Search
search_provider: algolia
algolia:
  application_id: 9WJHLYA4PB
  index_name: website_index
  search_only_api_key: 402ef1c119fc510124eeacddf70cacc0
  powered_by: true
  
  settings:
    searchableAttributes:
      - title
      - headings
      - unordered(content)
      - collection,categories,tags
      - unordered(html)
      - unordered(type)
      - unordered(categories)
    attributesToHighlight:
      - categories
      - content
      - headings
      - html
      - tags
      - title
      - type


analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-YYXNR5JLN8"
    anonymize_ip: false # default


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: null # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jonathan Rogers"
  avatar : "/assets/images/bio-photo.jpg"
  links:
    - label: "Email"
      icon: "far fa-envelope-open"
      url: "mailto:jrogers4895@cabarrus.k12.nc.us"
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/jonathan-rogers-549142192/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jonathan-rogers-dev"

footer:
  links:
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/jonathan-rogers-549142192/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jonathan-rogers-dev"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: false

# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
